### PR TITLE
Cosmetics & bugfix

### PR DESCRIPTION
**Pull request by sofianehaddad**
Mainly cosmetics : use the same notation for correlation lengths & variances
Also fix kriging conditional variance: add the missing term in case of trend estimate

### CODE REVIEW

**Comment by mbaudin47** [comment]
Thank you very much Sofiane!

**Comment by mbaudin47** [comment]
This sounds OK for me. Do you validate @chuvanmai?

**Comment by chuvanmai** [comment]
Thank you Sofiane for fixing the bugs, especially the one regarding the variance.

**Comment by sofianehaddad** [comment]
welcome

**Pull request merged**
